---
- hosts: all # comes from the hosts file
  become: true # become sudo
  gather_facts: false # save time and not gather info

  tasks:
    - name: set sudo password
      set_fact:
        ansible_sudo_pass: "{{ ansible_ssh_pass }}"

    - name: copy Dockerfile from Jenkins to target host
      copy:
        src: /var/lib/jenkins/workspace/Sofiane-Deploy-on-Container-using-Ansible-with-SonarQube/Dockerfile
        dest: /opt/docker

    - name: copy war from Jenkins to target host
      copy:
        src: /var/lib/jenkins/workspace/Sofiane-Deploy-on-Container-using-Ansible-with-SonarQube/target/webapp.war
        dest: /opt/docker

    - name: stop current container
      command: docker stop sofiane-devops-container-2
      ignore_errors: yes # in case container doesn’t exist

    - name: remove stopped container
      command: docker rm sofiane-devops-container-2
      ignore_errors: yes # in case container doesn’t exist

    - name: remove docker images 
      command: docker rmi sofiane-devops-image-2:latest
      ignore_errors: yes # in case image does not exist

    - name: create docker image using war file
      command: docker build -t sofiane-devops-image-2:latest .
      args:
        chdir: /opt/docker

    - name: run container from docker image
      command: docker run -d --name sofiane-devops-container-2 -p 8082:8080 sofiane-devops-image-2:latest
